version: "3.3"

volumes:
  osoon_logs:
  osoon_test_logs:
  osoon_pgsql:
  osoon_test_pgsql:

services:
  pgsql:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: osoon
      POSTGRES_PASSWORD: osoon
      POSTGRES_DB: osoon
      PGDATA: /data/postgres
    volumes:
      - osoon_pgsql:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: always

  pgsql-test:
    image: postgres:alpine
    environment:
      POSTGRES_USER: osoontest
      POSTGRES_PASSWORD: osoontest
      POSTGRES_DB: osoontest
      PGDATA: /data/postgres
    volumes:
      - osoon_test_pgsql:/data/postgres
    ports:
      - "6432:5432"
    restart: always

  backend:
    image: maven:3.5.2-jdk-8
    working_dir: /www
    command: mvn spring-boot:run
    ports:
      - "8080:8080"
    volumes:
      - ./src:/www/src
      - ./pom.xml:/www/pom.xml
    depends_on:
      - pgsql
    links:
      - pgsql:pgsql

  frontend:
    image: node:8.7.0
    working_dir: /www
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./web:/www
    depends_on:
      - backend
    links:
      - backend:backend

networks:
  postgres:
    driver: bridge
